version: '3'
  
networks:
  bridged:
    driver: bridge

services:
  gdal2tiles:
    container_name: gdal2tiles
    image: mambo/gdal2tiles
    networks:
      - bridged
    logging:
      options:
        max-size: 4m
        max-file: "10"
    volumes:
      - /opt/mambo/imagery/tmp_orthophoto_tif:/data/input
      - /opt/mambo/tiles:/data/output
  opendronemap:
    container_name: opendronemap
    image: mambo/opendronemapd:latest
    networks:
      - bridged
    logging:
      options:
        max-size: 4m
        max-file: "10"
    volumes:
      - /opt/mambo/imagery/tmp_drone_imgs:/code/images
      - /opt/mambo/imagery/tmp_orthophoto_tif:/code/odm_orthophoto
      - /opt/mambo/imagery/tmp_orthophoto_texturing:/code/odm_texturing
  mambo-api:
    container_name: mambo-api
    image: mambo/mambo-api:latest
    networks:
      - bridged
    ports:
      - "3000:3000"
    logging:
      options:
        max-size: 4m
        max-file: "10"
    volumes:
      - /opt/mambo/imagery/tmp_drone_imgs:/opt/mambo/imagery/images
      - /opt/mambo/imagery/tmp_orthophoto_tif:/opt/mambo/imagery/orthophoto
