---
- name: Install python setup tools
  yum: name=python-setuptools

- name: Install pypi
  easy_install: name=pip

- name: Install yum utils
  yum: name=yum-utils state=latest

- name: Install device-mapper
  yum: name=device-mapper-persistent-data state=latest

- name: Install lvm2
  yum: name=lvm2 state=latest
    
- name: Add docker-ce repository
  yum_repository: 
   name: docker-ce-repo
   description: Docker CE repository for CentOS
   gpgkey: https://download.docker.com/linux/centos/gpg
   baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/

- name: Install docker-ce
  yum: name=docker-ce state=latest
  
- name: Install docker-py
  pip: name=docker
  
- name: Install docker-compose
  pip: name=docker-compose

- name: Add current user to docker group
  user:
    name: "{{ansible_user}}"
    groups: docker
    append: yes

- name: Make sure Docker is running
  service: 
    name: docker 
    state: started 
    enabled: yes
