---
- name: "Create mambo resources directory"
  file: path=/opt/mambo/imagery state=directory mode=0755
- name: "Create mambo conf directory"
  file: path=/etc/mambo state=directory mode=0755
- name: Copy mambo docker-compose file
  copy: src=mambo.yml dest=/opt/mambo/mambo.yml
- name: Copy mambo service
  copy: src=mambo.service dest=/etc/systemd/system/mambo.service
- name: Copy mambo docker image opendronemapd
  copy: src=opendronemapd/ dest=/opt/mambo/opendronemapd/ directory_mode=0755
- name: Copy mambo docker images gdal2tiles
  copy: src=gdal2tiles/ dest=/opt/mambo/gdal2tiles/ directory_mode=0755
- name: Build docker image for opendronemapd
  shell: docker build -t mambo/opendronemapd /opt/mambo/opendronemapd
- name: Build docker image for gdal2tiles
  shell: docker build -t mambo/gdal2tiles /opt/mambo/gdal2tiles
- name: Build docker image for mambo Api
  shell: docker build -t mambo/mambo-api /vagrant/api
- name: Assign rights to services
  shell: chmod 755 -R /etc/systemd/system
